from enum import Enum


class MandateStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PARTIALLY_USED = "PARTIALLY_USED"
    EXHAUSTED = "EXHAUSTED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class ActionType(str, Enum):
    PAYMENT = "PAYMENT"
    REFUND = "REFUND"


class ActionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    STEP_UP_PENDING = "STEP_UP_PENDING"
    STEP_UP_APPROVED = "STEP_UP_APPROVED"
    STEP_UP_REJECTED = "STEP_UP_REJECTED"
    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PENDING_UNRESOLVED = "PENDING_UNRESOLVED"


class DecisionResult(str, Enum):
    ALLOW = "ALLOW"
    STEP_UP = "STEP_UP"
    BLOCK = "BLOCK"


class ReasonCode(str, Enum):
    # ALLOW path
    OK = "OK"

    # BLOCK reasons
    CAP_EXCEEDED = "CAP_EXCEEDED"
    WINDOW_EXHAUSTED = "WINDOW_EXHAUSTED"
    OUT_OF_SCOPE_CATEGORY = "OUT_OF_SCOPE_CATEGORY"
    PRICE_DRIFT = "PRICE_DRIFT"
    DUPLICATE_ACTION = "DUPLICATE_ACTION"
    MANDATE_EXPIRED = "MANDATE_EXPIRED"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    INVALID_MANDATE = "INVALID_MANDATE"
    SYSTEM_ERROR = "SYSTEM_ERROR"

    # STEP_UP reasons
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
